build:
  image: default-bionic
  environment:
    php:
      version: 8.1.2
      ini:
        xdebug.mode: coverage
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
    coverage:
      tests:
        override:
          - command: composer test-init && composer test-coverage-xml
            coverage:
              file: ./tests/_output/coverage.xml
              format: clover
tools:
  php_code_coverage: true
filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
coding_style:
  php:
    spaces:
      around_operators:
        additive: false
        multiplicative: false
